AWSTemplateFormatVersion: '2010-09-09'
Description: 'LLM Evaluation Infrastructure'

Resources:
  EvalBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-${AWS::AccountId}-eval"
      VersioningConfiguration:
        Status: Enabled
Outputs:
  BucketName:
    Value: !Ref EvalBucket